/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/components/guide/details/Features': RouteRecordInfo<'/components/guide/details/Features', '/components/guide/details/Features', Record<never, never>, Record<never, never>>,
    '/components/guide/details/Growing': RouteRecordInfo<'/components/guide/details/Growing', '/components/guide/details/Growing', Record<never, never>, Record<never, never>>,
    '/components/guide/details/ShortInfo': RouteRecordInfo<'/components/guide/details/ShortInfo', '/components/guide/details/ShortInfo', Record<never, never>, Record<never, never>>,
    '/components/guide/details/ShortNote': RouteRecordInfo<'/components/guide/details/ShortNote', '/components/guide/details/ShortNote', Record<never, never>, Record<never, never>>,
    '/components/guide/details/Signature': RouteRecordInfo<'/components/guide/details/Signature', '/components/guide/details/Signature', Record<never, never>, Record<never, never>>,
    '/components/guide/details/Similar': RouteRecordInfo<'/components/guide/details/Similar', '/components/guide/details/Similar', Record<never, never>, Record<never, never>>,
    '/components/guide/SearchBar': RouteRecordInfo<'/components/guide/SearchBar', '/components/guide/SearchBar', Record<never, never>, Record<never, never>>,
    '/components/indoor/detail/components/WaterCycle': RouteRecordInfo<'/components/indoor/detail/components/WaterCycle', '/components/indoor/detail/components/WaterCycle', Record<never, never>, Record<never, never>>,
    '/components/indoor/detail/FlowerNFruit': RouteRecordInfo<'/components/indoor/detail/FlowerNFruit', '/components/indoor/detail/FlowerNFruit', Record<never, never>, Record<never, never>>,
    '/components/indoor/detail/GrowCondition': RouteRecordInfo<'/components/indoor/detail/GrowCondition', '/components/indoor/detail/GrowCondition', Record<never, never>, Record<never, never>>,
    '/components/indoor/detail/GrowManage': RouteRecordInfo<'/components/indoor/detail/GrowManage', '/components/indoor/detail/GrowManage', Record<never, never>, Record<never, never>>,
    '/components/indoor/detail/IndoorCharacter': RouteRecordInfo<'/components/indoor/detail/IndoorCharacter', '/components/indoor/detail/IndoorCharacter', Record<never, never>, Record<never, never>>,
    '/components/indoor/detail/LeafInfo': RouteRecordInfo<'/components/indoor/detail/LeafInfo', '/components/indoor/detail/LeafInfo', Record<never, never>, Record<never, never>>,
    '/components/indoor/detail/LevelDifficulty': RouteRecordInfo<'/components/indoor/detail/LevelDifficulty', '/components/indoor/detail/LevelDifficulty', Record<never, never>, Record<never, never>>,
    '/components/indoor/detail/Outline': RouteRecordInfo<'/components/indoor/detail/Outline', '/components/indoor/detail/Outline', Record<never, never>, Record<never, never>>,
    '/components/indoor/detail/ShortInfo': RouteRecordInfo<'/components/indoor/detail/ShortInfo', '/components/indoor/detail/ShortInfo', Record<never, never>, Record<never, never>>,
    '/components/indoor/IndoorThumbnailSwiper': RouteRecordInfo<'/components/indoor/IndoorThumbnailSwiper', '/components/indoor/IndoorThumbnailSwiper', Record<never, never>, Record<never, never>>,
    '/components/indoor/SearchBarDetail': RouteRecordInfo<'/components/indoor/SearchBarDetail', '/components/indoor/SearchBarDetail', Record<never, never>, Record<never, never>>,
    '/components/indoor/SearchFilter': RouteRecordInfo<'/components/indoor/SearchFilter', '/components/indoor/SearchFilter', Record<never, never>, Record<never, never>>,
    '/components/main/MainSlider': RouteRecordInfo<'/components/main/MainSlider', '/components/main/MainSlider', Record<never, never>, Record<never, never>>,
    '/guide': RouteRecordInfo<'/guide', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/': RouteRecordInfo<'/guide/', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/detail/[code]/': RouteRecordInfo<'/guide/detail/[code]/', '/guide/detail/:code', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    '/guide/detail/[code]/components/GuideDetail': RouteRecordInfo<'/guide/detail/[code]/components/GuideDetail', '/guide/detail/:code/components/GuideDetail', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    '/indoor': RouteRecordInfo<'/indoor', '/indoor', Record<never, never>, Record<never, never>>,
    '/indoor/': RouteRecordInfo<'/indoor/', '/indoor', Record<never, never>, Record<never, never>>,
    '/indoor/detail/[name]/': RouteRecordInfo<'/indoor/detail/[name]/', '/indoor/detail/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/indoor/detail/[name]/components/IndoorDetail': RouteRecordInfo<'/indoor/detail/[name]/components/IndoorDetail', '/indoor/detail/:name/components/IndoorDetail', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/member': RouteRecordInfo<'/member', '/member', Record<never, never>, Record<never, never>>,
    '/member/find/': RouteRecordInfo<'/member/find/', '/member/find', Record<never, never>, Record<never, never>>,
    '/member/join/': RouteRecordInfo<'/member/join/', '/member/join', Record<never, never>, Record<never, never>>,
    '/member/login/': RouteRecordInfo<'/member/login/', '/member/login', Record<never, never>, Record<never, never>>,
    '/member/verify/': RouteRecordInfo<'/member/verify/', '/member/verify', Record<never, never>, Record<never, never>>,
    '/verify': RouteRecordInfo<'/verify', '/verify', Record<never, never>, Record<never, never>>,
  }
}
