/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/components/details/Features': RouteRecordInfo<'/components/details/Features', '/components/details/Features', Record<never, never>, Record<never, never>>,
    '/components/details/Growing': RouteRecordInfo<'/components/details/Growing', '/components/details/Growing', Record<never, never>, Record<never, never>>,
    '/components/details/SearchBar': RouteRecordInfo<'/components/details/SearchBar', '/components/details/SearchBar', Record<never, never>, Record<never, never>>,
    '/components/details/ShortInfo': RouteRecordInfo<'/components/details/ShortInfo', '/components/details/ShortInfo', Record<never, never>, Record<never, never>>,
    '/components/details/ShortNote': RouteRecordInfo<'/components/details/ShortNote', '/components/details/ShortNote', Record<never, never>, Record<never, never>>,
    '/components/details/Signature': RouteRecordInfo<'/components/details/Signature', '/components/details/Signature', Record<never, never>, Record<never, never>>,
    '/components/details/Similar': RouteRecordInfo<'/components/details/Similar', '/components/details/Similar', Record<never, never>, Record<never, never>>,
    '/components/main/MainSlider': RouteRecordInfo<'/components/main/MainSlider', '/components/main/MainSlider', Record<never, never>, Record<never, never>>,
    '/guide': RouteRecordInfo<'/guide', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/': RouteRecordInfo<'/guide/', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/detail/[code]/': RouteRecordInfo<'/guide/detail/[code]/', '/guide/detail/:code', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    '/guide/detail/[code]/components/PlantDetail': RouteRecordInfo<'/guide/detail/[code]/components/PlantDetail', '/guide/detail/:code/components/PlantDetail', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    '/indoor': RouteRecordInfo<'/indoor', '/indoor', Record<never, never>, Record<never, never>>,
    '/indoor/': RouteRecordInfo<'/indoor/', '/indoor', Record<never, never>, Record<never, never>>,
    '/member': RouteRecordInfo<'/member', '/member', Record<never, never>, Record<never, never>>,
    '/member/join/': RouteRecordInfo<'/member/join/', '/member/join', Record<never, never>, Record<never, never>>,
    '/member/login/': RouteRecordInfo<'/member/login/', '/member/login', Record<never, never>, Record<never, never>>,
    '/member/verify/': RouteRecordInfo<'/member/verify/', '/member/verify', Record<never, never>, Record<never, never>>,
    '/verify': RouteRecordInfo<'/verify', '/verify', Record<never, never>, Record<never, never>>,
  }
}
